version: "3"

services:
  valheim-server:
    image: evirth/valheim-server-pi4
    container_name: valheim-server
    env_file:
      - server.env
    ports:
      - "2456-2457:2456-2457/udp"
      - "2456-2457:2456-2457/tcp"
    volumes:
      - "valheim-data:/root/valheim_server"
    restart: unless-stopped

volumes:
  valheim-data:
    name: valheim-data